test:
  tags:
    - shared-fi
  image: rust:latest
  before_script:
    - wget https://www.cs.utexas.edu/~marijn/drat-trim/drat-trim.c
    - gcc -O2 -o drat-trim drat-trim.c
    - install drat-trim /usr/bin/
  script:
    - cargo test --release -- --include-ignored
